trigger:
- main

schedules:
- cron: "0 2 * * 1-5"
  displayName: Weekday Build
  branches:
    include:
    - main
  always: true

resources:
  repositories:
  - repository: templates
    type: git
    endpoint: soadoc-azure-repos
    name: UENSOADOC_202400000011%20EVOLUTIVOS%20PRODUCTO/pipeline-templates
    ref: refs/heads/main

variables:
  - template: variables/variables.yml@templates

pool:
  vmImage: 'ubuntu-latest'
  
stages:
 - stage: BuildDockerImage
   jobs:
   - job: BuildVulnzClient
     steps:
      - script : |
          export VULNZ_VERSION=6.1.7
          ./gradlew vulnz:build -Pversion=$VULNZ_VERSION

          docker build vulnz/ -t $(REGISTRY_DEV)/vulnz:$VULNZ_VERSION --build-arg BUILD_VERSION=$VULNZ_VERSION \
                              --build-arg nvm_api_key=$(NVD_API_KEY) \
                              --build-arg cache_date="$(date)"

      - template: ../steps/step-docker-login.yml
        parameters:
          registryUser: '$(REGISTRY_USER)'
          registryPassword: '$(REGISTRY_DEV_PSW)'
          containerRegistry: '$(REGISTRY_DEV)'

      - template: ../steps/step-docker-push.yml
        parameters:
          containerRegistry: '$(REGISTRY_DEV)'
          imageName: '$(REGISTRY_DEV)/vulnz:$VULNZ_VERSION'
          
      

