trigger:
- main

schedules:
- cron: "0 2 * * 1-5"
  displayName: Weekday Build
  branches:
    include:
    - main
  always: true

resources:
  repositories:
  - repository: templates
    type: git
    endpoint: soadoc-azure-repos
    name: UENSOADOC_202400000011%20EVOLUTIVOS%20PRODUCTO/pipeline-templates
    ref: refs/heads/main

variables:
  - template: variables/variables.yml@templates

pool:
  vmImage: 'ubuntu-latest'
  
stages:
 - stage: BuildDockerImage
   jobs:
   - job: BuildVulnzClient
     steps:
      - script : |
          export VULNZ_VERSION=$(VULNZ_VERSION)
          ./gradlew vulnz:build -Pversion=$VULNZ_VERSION
        displayName: Compilado de proyecto vulnz
      
      - script : |
          docker build vulnz/ -t $(REGISTRY_DEV)/vulnz:$(VULNZ_VERSION) --build-arg BUILD_VERSION=$(VULNZ_VERSION) \
                              --build-arg nvm_api_key=$(NVD_API_KEY) \
                              --build-arg cache_date="$(date)"
        displayName: Construyendo Imagen Docker para vulnz

      - template: steps/step-docker-login.yml@templates
        parameters:
          registryUser: '$(REGISTRY_USER)'
          registryPassword: '$(REGISTRY_DEV_PSW)'
          containerRegistry: '$(REGISTRY_DEV)'

      - template: steps/step-docker-push.yml@templates
        parameters:
          containerRegistry: '$(REGISTRY_DEV)'
          imageName: 'vulnz:$(VULNZ_VERSION)'
          
      

