apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnz
  namespace: ns-aks-soadoc-monitoring
  annotations:
    meta.helm.sh/release-name: vulnz
    meta.helm.sh/release-namespace: ns-aks-soadoc-monitoring
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnz
  template:
    metadata:
      labels:
        app: vulnz
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - intpool
      containers:
      - name: vulnz
        image: acrproductosoaintdev.azurecr.io/vulnz:6.1.7
        imagePullPolicy: Always       
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: 10m
            memory: 15Mi
          requests:
            cpu: 10m
            memory: 6Mi
